### PR TITLE
Fix search draft discarding first character

### LINKED ISSUE #229: First letter of search draft is removed when closing chat - 215.6.14-secure - 1.21.5
### Description
With search drafting enabled, closing out of chat will remove the first character from the search box. Opening and closing chat repeatedly will eventually remove the entire draft.

### How to reproduce
1. Enable Search drafting toggle in settings (on by default)
2. Open chat
3. Enter some characters into the search box
4. Close out of chat (by pressing escape or sending a message)
5. Open chat again, and the search string will now be missing the first character. For example, `Search` -> `earch`.

### Expected result
Drafting should keep the whole search string instead of removing the first letter.

### Log file link
Probably not applicable, but: https://mclo.gs/ZLOXprf

### Specs and Details
Required information:
- OS: Windows 11 Pro 10.0.22631 Build 22631
- Mod version: 215.6.14-secure
- Fabric version: 0.16.14
- Fabric API version: 0.121.0+1.21.5
- YetAnotherConfigLib version: 3.6.6+1.21.5-fabric
- Mod Menu version: 14.0.0-rc.2

### PR DESCRIPTION
**Pull request by collin-b1**
Fixes #229. Removes substring function from search draft string.

### CODE REVIEW

File: src/main/java/obro1961/chatpatches/mixin/gui/ChatScreenMixin.java [hunk 1]
```diff
@@ -165,8 +165,11 @@ protected void initSearchStuff(CallbackInfo ci) {
 		searchField.setDrawsBackground(false);
 		searchField.setSuggestion(SEARCH_SUGGESTION);
 		searchField.setChangedListener(newText -> onSearchFieldUpdate(newText, false));
-		if(config.searchDrafting)
-			searchField.setText( searchDraft.length() > 1 ? searchDraft.substring(1) : "" ); // remove the null char from the draft
+		if(config.searchDrafting) {
+			searchField.setText(!searchDraft.isEmpty() ? searchDraft : "" );
```
Comment (collin-b1) [inline src/main/java/obro1961/chatpatches/mixin/gui/ChatScreenMixin.java]: The null char mentioned in the original comment doesn't seem to be present. Therefore, `.substring(1)` should be removed, and `searchDraft.length() > 1` should be changed to `searchDraft.length > 0`, or `!searchDraft.isEmpty()`.

File: src/main/java/obro1961/chatpatches/mixin/gui/ChatScreenMixin.java [hunk 2]
```diff
@@ -165,8 +165,11 @@ protected void initSearchStuff(CallbackInfo ci) {
...
+			if (!searchDraft.isEmpty())
+				onSearchFieldUpdate(searchField.getText(), true);
```
Comment (collin-b1) [inline src/main/java/obro1961/chatpatches/mixin/gui/ChatScreenMixin.java:171]: Added a forced `onSearchFieldUpdate(...)` to fix a new problem that the above change created. Originally, the substring-ed search draft would get added, and since the substring-ed version doesn't match the actual stored draft, it counted as an update and would call `onSearchFieldUpdate(...)`. After getting rid of substring, there is no change to the search draft, which causes the result color to not show, and the "Search..." suggestion/placeholder to display at the end of the search draft. 

This forces the color to show and "Search..." to not show after exiting and reentering chat with a saved search draft.

**Comment by mrbuilder1961** [comment]
thanks for the PR! i appreciate the thorough explanations with your changes, it makes this process almost effortless! i'll test out your fix asap and approve it accordingly 😄

File: src/main/java/obro1961/chatpatches/mixin/gui/ChatScreenMixin.java (hunk 1 above)
Comment (mrbuilder1961) [reply src/main/java/obro1961/chatpatches/mixin/gui/ChatScreenMixin.java]: is there a reason the parameter passed to `setText(String)` can't just be simplified to `searchDraft`? the `isEmpty()` check seems useless here
